/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sequality;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    Calculate cal = new Calculate();
    double a=cal.sum
    System.out.println(new App().getGreeting());
  }
}
